<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['name' => 'Afghanistan', 'country_code' => 93],
            ['name' => 'Albania', 'country_code' => 355],
            ['name' => 'Algeria', 'country_code' => 213],
            ['name' => 'Andorra', 'country_code' => 376],
            ['name' => 'Angola', 'country_code' => 244],
            ['name' => 'Antigua and Barbuda', 'country_code' => 1268],
            ['name' => 'Argentina', 'country_code' => 54],
            ['name' => 'Armenia', 'country_code' => 374],
            ['name' => 'Australia', 'country_code' => 61],
            ['name' => 'Austria', 'country_code' => 43],
            ['name' => 'Azerbaijan', 'country_code' => 994],
            ['name' => 'Bahamas', 'country_code' => 1242],
            ['name' => 'Bahrain', 'country_code' => 973],
            ['name' => 'Bangladesh', 'country_code' => 880],
            ['name' => 'Barbados', 'country_code' => 1246],
            ['name' => 'Belarus', 'country_code' => 375],
            ['name' => 'Belgium', 'country_code' => 32],
            ['name' => 'Belize', 'country_code' => 501],
            ['name' => 'Benin', 'country_code' => 229],
            ['name' => 'Bhutan', 'country_code' => 975],
            ['name' => 'Bolivia', 'country_code' => 591],
            ['name' => 'Bosnia and Herzegovina', 'country_code' => 387],
            ['name' => 'Botswana', 'country_code' => 267],
            ['name' => 'Brazil', 'country_code' => 55],
            ['name' => 'Brunei', 'country_code' => 673],
            ['name' => 'Bulgaria', 'country_code' => 359],
            ['name' => 'Burkina Faso', 'country_code' => 226],
            ['name' => 'Burundi', 'country_code' => 257], 
            ['name' => 'Cambodia', 'country_code' => 855],
            ['name' => 'Cameroon', 'country_code' => 237],
            ['name' => 'Canada', 'country_code' => 1],
            ['name' => 'Cape Verde', 'country_code' => 238],
            ['name' => 'Cayman Islands', 'country_code' => 1345],
            ['name' => 'Central African Republic', 'country_code' => 236],
            ['name' => 'Chad', 'country_code' => 235],
            ['name' => 'Chile', 'country_code' => 56],
            ['name' => 'China', 'country_code' => 86],
            ['name' => 'Cocos (Keeling) Islands', 'country_code' => 672],
            ['name' => 'Colombia', 'country_code' => 57],
            ['name' => 'Comoros', 'country_code' => 269],
            ['name' => 'Congo', 'country_code' => 242],
            ['name' => 'Cook Islands', 'country_code' => 682],
            ['name' => 'Costa Rica', 'country_code' => 506],
            ['name' => 'Cote D”Ivoire', 'country_code' => 225],
            ['name' => 'Croatia', 'country_code' => 385],
            ['name' => 'Cuba', 'country_code' => 53],
            ['name' => 'Cyprus', 'country_code' => 357],
            ['name' => 'Czech Republic', 'country_code' => 420],
            ['name' => 'Denmark', 'country_code' => 45],
            ['name' => 'Djibouti', 'country_code' => 253],
            ['name' => 'Dominica', 'country_code' => 1767],
            ['name' => 'Dominican Republic', 'country_code' => 1809],

            ['name' => 'Ecuador', 'country_code' => 593],
            ['name' => 'Egypt', 'country_code' => 20],
            ['name' => 'El Salvador', 'country_code' => 503],
            ['name' => 'Equatorial Guinea', 'country_code' => 240],
            ['name' => 'Eritrea', 'country_code' => 291],
            ['name' => 'Estonia', 'country_code' => 372],
            ['name' => 'Ethiopia', 'country_code' => 251],
            ['name' => 'Falkland Islands (Malvinas)', 'country_code' => 500],
            ['name' => 'Faroe Islands', 'country_code' => 298],
            ['name' => 'Fiji', 'country_code' => 679],
            ['name' => 'Finland', 'country_code' => 358],
            ['name' => 'France', 'country_code' => 33],
            ['name' => 'French Guiana', 'country_code' => 594],
            ['name' => 'French Polynesia', 'country_code' => 689],
            ['name' => 'Gabon', 'country_code' => 241],
            ['name' => 'Gambia', 'country_code' => 220],
            ['name' => 'Georgia', 'country_code' => 995],
            ['name' => 'Germany', 'country_code' => 49],
            ['name' => 'Ghana', 'country_code' => 233],
            ['name' => 'Gibraltar', 'country_code' => 350],
            ['name' => 'Greece', 'country_code' => 30],
            ['name' => 'Greenland', 'country_code' => 299],
            ['name' => 'Grenada', 'country_code' => 1473],
            ['name' => 'Guadeloupe', 'country_code' => 590],
            ['name' => 'Guam', 'country_code' => 1671],
            ['name' => 'Guatemala', 'country_code' => 502],
            ['name' => 'Guinea', 'country_code' => 224],
            ['name' => 'Guinea-Bissau', 'country_code' => 245],
            ['name' => 'Guyana', 'country_code' => 592],
            ['name' => 'Haiti', 'country_code' => 509],
            ['name' => 'Honduras', 'country_code' => 504],
            ['name' => 'Hong Kong', 'country_code' => 852],
            ['name' => 'Hungary', 'country_code' => 36],
            ['name' => 'Iceland', 'country_code' => 354],
            ['name' => 'India', 'country_code' => 91],
            ['name' => 'Indonesia', 'country_code' => 62],
            ['name' => 'Iran, Islamic Republic of', 'country_code' => 98],
            ['name' => 'Iraq', 'country_code' => 964],
            ['name' => 'Ireland', 'country_code' => 353],
            ['name' => 'Israel', 'country_code' => 972],
            ['name' => 'Italy', 'country_code' => 39],
            ['name' => 'Jamaica', 'country_code' => 1876],
            ['name' => 'Japan', 'country_code' => 81],
            ['name' => 'Jordan', 'country_code' => 962],
            ['name' => 'Kazakhstan', 'country_code' => 7],
            ['name' => 'Kenya', 'country_code' => 254],
            ['name' => 'Kiribati', 'country_code' => 686],
            ['name' => 'Korea, Democratic People"s Republic of', 'country_code'=>850],
            ['name' => 'Korea, Republic of', 'country_code' => 82],
            ['name' => 'Kuwait', 'country_code' => 965],
            ['name' => 'Kyrgyzstan', 'country_code' => 996],
            ['name' => 'Lao People"s Democratic Republic', 'country_code' => 856],
            ['name' => 'Latvia', 'country_code' => 371],
            ['name' => 'Lebanon', 'country_code' => 961],
            ['name' => 'Lesotho', 'country_code' => 266],
            ['name' => 'Liberia', 'country_code' => 231],
            ['name' => 'Libyan Arab Jamahiriya', 'country_code' => 218],
            ['name' => 'Liechtenstein', 'country_code' => 423],
            ['name' => 'Lithuania', 'country_code' => 370],
            ['name' => 'Luxembourg', 'country_code' => 352],
            ['name' => 'Macao', 'country_code' => 853],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'country_code' => 389],
            ['name' => 'Madagascar', 'country_code' => 261],
            ['name' => 'Malawi', 'country_code' => 265],
            ['name' => 'Malaysia', 'country_code' => 60],
            ['name' => 'Maldives', 'country_code' => 960],
            ['name' => 'Mali', 'country_code' => 223],
            ['name' => 'Malta', 'country_code' => 356],
            ['name' => 'Marshall Islands', 'country_code' => 692],
            ['name' => 'Martinique', 'country_code' => 596],
            ['name' => 'Mauritania', 'country_code' => 222],
            ['name' => 'Mauritius', 'country_code' => 230],
            ['name' => 'Mexico', 'country_code' => 52],
            ['name' => 'Micronesia, Federated States of', 'country_code' => 691],
            ['name' => 'Moldova, Republic of', 'country_code' => 373],
            ['name' => 'Monaco', 'country_code' => 377],
            ['name' => 'Mongolia', 'country_code' => 976],
            ['name' => 'Montserrat', 'country_code' => 1664],
            ['name' => 'Morocco', 'country_code' => 212],
            ['name' => 'Mozambique', 'country_code' => 258],
            ['name' => 'Myanmar', 'country_code' => 95],
            ['name' => 'Namibia', 'country_code' => 264],
            ['name' => 'Nauru', 'country_code' => 674],
            ['name' => 'Nepal', 'country_code' => 977],
            ['name' => 'Netherlands', 'country_code' => 31],
            ['name' => 'Netherlands Antilles', 'country_code' => 599],
            ['name' => 'New Caledonia', 'country_code' => 687],
            ['name' => 'New Zealand', 'country_code' => 64],
            ['name' => 'Nicaragua', 'country_code' => 505],
            ['name' => 'Niger', 'country_code' => 227],
            ['name' => 'Nigeria', 'country_code' => 234],
            ['name' => 'Niue', 'country_code' => 683],
            ['name' => 'Northern Mariana Islands', 'country_code' => 1670],
            ['name' => 'Norway', 'country_code' => 47],
            ['name' => 'Oman', 'country_code' => 968],
            ['name' => 'Pakistan', 'country_code' => 92],
            ['name' => 'Palau', 'country_code' => 680],
            ['name' => 'Panama', 'country_code' => 507],
            ['name' => 'Papua New Guinea', 'country_code' => 675],
            ['name' => 'Paraguay', 'country_code' => 595],
            ['name' => 'Peru', 'country_code' => 51],
            ['name' => 'Philippines', 'country_code' => 63],
            ['name' => 'Poland', 'country_code' => 48],
            ['name' => 'Portugal', 'country_code' => 351],
            ['name' => 'Puerto Rico', 'country_code' => 1787],
            ['name' => 'Qatar', 'country_code' => 974],
            ['name' => 'Reunion', 'country_code' => 262],
            ['name' => 'Romania', 'country_code' => 40],
            ['name' => 'Russian Federation', 'country_code' => 70],
            ['name' => 'Rwanda', 'country_code' => 250],
            ['name' => 'Saint Helena', 'country_code' => 290],
            ['name' => 'Saint Kitts and Nevis', 'country_code' => 1869],
            ['name' => 'Saint Lucia', 'country_code' => 1758],
            ['name' => 'Saint Pierre and Miquelon', 'country_code' => 508],
            ['name' => 'Saint Vincent and the Grenadines', 'country_code' => 1784],
            ['name' => 'Samoa', 'country_code' => 684],
            ['name' => 'San Marino', 'country_code' => 378],
            ['name' => 'Sao Tome and Principe', 'country_code' => 239],
            ['name' => 'Saudi Arabia', 'country_code' => 966],
            ['name' => 'Senegal', 'country_code' => 221],
            ['name' => 'Serbia', 'country_code' => 381],
            ['name' => 'Seychelles', 'country_code' => 248],
            ['name' => 'Sierra Leone', 'country_code' => 232],
            ['name' => 'Singapore', 'country_code' => 65],
            ['name' => 'Slovakia', 'country_code' => 421],
            ['name' => 'Slovenia', 'country_code' => 386],
            ['name' => 'Solomon Islands', 'country_code' => 677],
            ['name' => 'Somalia', 'country_code' => 252],
            ['name' => 'South Africa', 'country_code' => 27],
            ['name' => 'Spain', 'country_code' => 34],
            ['name' => 'Sri Lanka', 'country_code' => 94],
            ['name' => 'Sudan', 'country_code' => 249],
            ['name' => 'Suriname', 'country_code' => 597],
            ['name' => 'Swaziland', 'country_code' => 268],
            ['name' => 'Sweden', 'country_code' => 46],
            ['name' => 'Switzerland', 'country_code' => 41],
            ['name' => 'Syrian Arab Republic', 'country_code' => 963],
            ['name' => 'Taiwan, Province of China', 'country_code' => 886],
            ['name' => 'Tajikistan', 'country_code' => 992],
            ['name' => 'Tanzania, United Republic of', 'country_code' => 255],
            ['name' => 'Thailand', 'country_code' => 66],
            ['name' => 'Timor-Leste', 'country_code' => 670],
            ['name' => 'Togo', 'country_code' => 228],
            ['name' => 'Tokelau', 'country_code' => 690],
            ['name' => 'Tonga', 'country_code' => 676],
            ['name' => 'Trinidad and Tobago', 'country_code' => 1868],
            ['name' => 'Tunisia', 'country_code' => 216],
            ['name' => 'Turkey', 'country_code' => 90],
            ['name' => 'Turkmenistan', 'country_code' => 993],
            ['name' => 'Turks and Caicos Islands', 'country_code' => 1649],
            ['name' => 'Tuvalu', 'country_code' => 688],
            ['name' => 'Uganda', 'country_code' => 256],
            ['name' => 'Ukraine', 'country_code' => 380],
            ['name' => 'United Arab Emirates', 'country_code' => 971],
            ['name' => 'United Kingdom', 'country_code' => 44],
            ['name' => 'United States', 'country_code' => 1],
            ['name' => 'Uruguay', 'country_code' => 598],
            ['name' => 'Uzbekistan', 'country_code' => 998],
            ['name' => 'Vanuatu', 'country_code' => 678],
            ['name' => 'Venezuela', 'country_code' => 58],
            ['name' => 'Viet Nam', 'country_code' => 84],
            ['name' => 'Virgin Islands, British', 'country_code' => 1284],
            ['name' => 'Virgin Islands, U.S.', 'country_code' => 1340],
            ['name' => 'Yemen', 'country_code' => 967],
            ['name' => 'Zambia', 'country_code' => 260],
            ['name' => 'Zimbabwe', 'country_code'=>263],
            // ... وهكذا لبقية الدول
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'name' => $country['name'],
                'country_code' => $country['country_code']
            ]);
        }
    }
}
